// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { AntiAffinityGroupVMArgs } from "./antiAffinityGroupVM";
export type AntiAffinityGroupVM = import("./antiAffinityGroupVM").AntiAffinityGroupVM;
export const AntiAffinityGroupVM: typeof import("./antiAffinityGroupVM").AntiAffinityGroupVM = null as any;
utilities.lazyLoad(exports, ["AntiAffinityGroupVM"], () => require("./antiAffinityGroupVM"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "vco:anti_affinity_group:AntiAffinityGroupVM":
                return new AntiAffinityGroupVM(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("vco", "anti_affinity_group", _module)
