// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Virtual_machine
{
    [VcoResourceType("vco:virtual_machine:VirtualMachineCD")]
    public partial class VirtualMachineCD : global::Pulumi.CustomResource
    {
        [Output("cdrom_id")]
        public Output<int> Cdrom_id { get; private set; } = null!;

        [Output("cloudspace_id")]
        public Output<string> Cloudspace_id { get; private set; } = null!;

        [Output("customerID")]
        public Output<string> CustomerID { get; private set; } = null!;

        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        [Output("disk_size")]
        public Output<string> Disk_size { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        [Output("vm_id")]
        public Output<int> Vm_id { get; private set; } = null!;


        /// <summary>
        /// Create a VirtualMachineCD resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VirtualMachineCD(string name, VirtualMachineCDArgs args, CustomResourceOptions? options = null)
            : base("vco:virtual_machine:VirtualMachineCD", name, args ?? new VirtualMachineCDArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VirtualMachineCD(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("vco:virtual_machine:VirtualMachineCD", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VirtualMachineCD resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VirtualMachineCD Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new VirtualMachineCD(name, id, options);
        }
    }

    public sealed class VirtualMachineCDArgs : global::Pulumi.ResourceArgs
    {
        [Input("cdrom_id", required: true)]
        public Input<int> Cdrom_id { get; set; } = null!;

        [Input("cloudspace_id", required: true)]
        public Input<string> Cloudspace_id { get; set; } = null!;

        [Input("customerID", required: true)]
        public Input<string> CustomerID { get; set; } = null!;

        [Input("token", required: true)]
        public Input<string> Token { get; set; } = null!;

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        [Input("vm_id", required: true)]
        public Input<int> Vm_id { get; set; } = null!;

        public VirtualMachineCDArgs()
        {
        }
        public static new VirtualMachineCDArgs Empty => new VirtualMachineCDArgs();
    }
}
