// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ExposedDiskArgs } from "./exposedDisk";
export type ExposedDisk = import("./exposedDisk").ExposedDisk;
export const ExposedDisk: typeof import("./exposedDisk").ExposedDisk = null as any;
utilities.lazyLoad(exports, ["ExposedDisk"], () => require("./exposedDisk"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "vco:disk:ExposedDisk":
                return new ExposedDisk(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("vco", "disk", _module)
