// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Ingress.Outputs
{

    [OutputType]
    public sealed class StickySessionCookie
    {
        public readonly bool? Http_only;
        public readonly string? Name;
        public readonly string? Same_site;
        public readonly bool? Secure;

        [OutputConstructor]
        private StickySessionCookie(
            bool? http_only,

            string? name,

            string? same_site,

            bool? secure)
        {
            Http_only = http_only;
            Name = name;
            Same_site = same_site;
            Secure = secure;
        }
    }
}
