// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package base

import (
	"context"
	"reflect"

	"github.com/fabianv-cloud/pulumi-vco-native/sdk/go/command/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type IOTune struct {
	Iops float64 `pulumi:"iops"`
}

type IOTuneOutput struct{ *pulumi.OutputState }

func (IOTuneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IOTune)(nil)).Elem()
}

func (o IOTuneOutput) ToIOTuneOutput() IOTuneOutput {
	return o
}

func (o IOTuneOutput) ToIOTuneOutputWithContext(ctx context.Context) IOTuneOutput {
	return o
}

func (o IOTuneOutput) Iops() pulumi.Float64Output {
	return o.ApplyT(func(v IOTune) float64 { return v.Iops }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterOutputType(IOTuneOutput{})
}
