// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Outputs
{

    [OutputType]
    public sealed class BackEndState
    {
        public readonly string Serverpool_id;
        public readonly string Serverpool_name;
        public readonly int Target_port;

        [OutputConstructor]
        private BackEndState(
            string serverpool_id,

            string serverpool_name,

            int target_port)
        {
            Serverpool_id = serverpool_id;
            Serverpool_name = serverpool_name;
            Target_port = target_port;
        }
    }
}
