// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Outputs
{

    [OutputType]
    public sealed class FrontEnd
    {
        public readonly string Ip_address;
        public readonly int Port;
        public readonly Outputs.TLS Tls;

        [OutputConstructor]
        private FrontEnd(
            string ip_address,

            int port,

            Outputs.TLS tls)
        {
            Ip_address = ip_address;
            Port = port;
            Tls = tls;
        }
    }
}
