// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Outputs
{

    [OutputType]
    public sealed class IOTune
    {
        public readonly double Iops;

        [OutputConstructor]
        private IOTune(double iops)
        {
            Iops = iops;
        }
    }
}
