// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Outputs
{

    [OutputType]
    public sealed class LetsEncrypt
    {
        public readonly string Email;
        public readonly bool Enabled;

        [OutputConstructor]
        private LetsEncrypt(
            string email,

            bool enabled)
        {
            Email = email;
            Enabled = enabled;
        }
    }
}
