// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Outputs
{

    [OutputType]
    public sealed class Options
    {
        public readonly Outputs.HealthCheck Health_check;
        public readonly Outputs.StickySessionCookie Sticky_session_cookie;

        [OutputConstructor]
        private Options(
            Outputs.HealthCheck health_check,

            Outputs.StickySessionCookie sticky_session_cookie)
        {
            Health_check = health_check;
            Sticky_session_cookie = sticky_session_cookie;
        }
    }
}
