// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Outputs
{

    [OutputType]
    public sealed class ReverseProxyFrontEnd
    {
        public readonly string Domain;
        public readonly int Http_port;
        public readonly int Https_port;
        public readonly string Ip_address;
        public readonly Outputs.LetsEncrypt Letsencrypt;
        public readonly string Scheme;

        [OutputConstructor]
        private ReverseProxyFrontEnd(
            string domain,

            int http_port,

            int https_port,

            string ip_address,

            Outputs.LetsEncrypt letsencrypt,

            string scheme)
        {
            Domain = domain;
            Http_port = http_port;
            Https_port = https_port;
            Ip_address = ip_address;
            Letsencrypt = letsencrypt;
            Scheme = scheme;
        }
    }
}
