// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Cloudspace
{
    [VcoResourceType("vco:cloudspace:PortForward")]
    public partial class PortForward : global::Pulumi.CustomResource
    {
        [Output("cloudspace_id")]
        public Output<string> Cloudspace_id { get; private set; } = null!;

        [Output("customerID")]
        public Output<string> CustomerID { get; private set; } = null!;

        [Output("local_port")]
        public Output<int> Local_port { get; private set; } = null!;

        [Output("nested_cs_id")]
        public Output<string> Nested_cs_id { get; private set; } = null!;

        [Output("portforward_id")]
        public Output<string> Portforward_id { get; private set; } = null!;

        [Output("protocol")]
        public Output<string> Protocol { get; private set; } = null!;

        [Output("public_ip")]
        public Output<string> Public_ip { get; private set; } = null!;

        [Output("public_port")]
        public Output<int> Public_port { get; private set; } = null!;

        [Output("till_public_port")]
        public Output<int> Till_public_port { get; private set; } = null!;

        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        [Output("vm_id")]
        public Output<int> Vm_id { get; private set; } = null!;


        /// <summary>
        /// Create a PortForward resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PortForward(string name, PortForwardArgs args, CustomResourceOptions? options = null)
            : base("vco:cloudspace:PortForward", name, args ?? new PortForwardArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PortForward(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("vco:cloudspace:PortForward", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PortForward resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PortForward Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PortForward(name, id, options);
        }
    }

    public sealed class PortForwardArgs : global::Pulumi.ResourceArgs
    {
        [Input("cloudspace_id", required: true)]
        public Input<string> Cloudspace_id { get; set; } = null!;

        [Input("customerID", required: true)]
        private Input<string>? _customerID;
        public Input<string>? CustomerID
        {
            get => _customerID;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _customerID = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("local_port", required: true)]
        public Input<int> Local_port { get; set; } = null!;

        [Input("nested_cs_id")]
        public Input<string>? Nested_cs_id { get; set; }

        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        [Input("public_ip", required: true)]
        public Input<string> Public_ip { get; set; } = null!;

        [Input("public_port", required: true)]
        public Input<int> Public_port { get; set; } = null!;

        [Input("till_public_port")]
        public Input<int>? Till_public_port { get; set; }

        [Input("token", required: true)]
        private Input<string>? _token;
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("url", required: true)]
        private Input<string>? _url;
        public Input<string>? Url
        {
            get => _url;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _url = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("vm_id", required: true)]
        public Input<int> Vm_id { get; set; } = null!;

        public PortForwardArgs()
        {
        }
        public static new PortForwardArgs Empty => new PortForwardArgs();
    }
}
