// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { HostArgs } from "./host";
export type Host = import("./host").Host;
export const Host: typeof import("./host").Host = null as any;
utilities.lazyLoad(exports, ["Host"], () => require("./host"));

export { LoadBalancerArgs } from "./loadBalancer";
export type LoadBalancer = import("./loadBalancer").LoadBalancer;
export const LoadBalancer: typeof import("./loadBalancer").LoadBalancer = null as any;
utilities.lazyLoad(exports, ["LoadBalancer"], () => require("./loadBalancer"));

export { ReverseProxyArgs } from "./reverseProxy";
export type ReverseProxy = import("./reverseProxy").ReverseProxy;
export const ReverseProxy: typeof import("./reverseProxy").ReverseProxy = null as any;
utilities.lazyLoad(exports, ["ReverseProxy"], () => require("./reverseProxy"));

export { ServerPoolArgs } from "./serverPool";
export type ServerPool = import("./serverPool").ServerPool;
export const ServerPool: typeof import("./serverPool").ServerPool = null as any;
utilities.lazyLoad(exports, ["ServerPool"], () => require("./serverPool"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "vco:ingress:Host":
                return new Host(name, <any>undefined, { urn })
            case "vco:ingress:LoadBalancer":
                return new LoadBalancer(name, <any>undefined, { urn })
            case "vco:ingress:ReverseProxy":
                return new ReverseProxy(name, <any>undefined, { urn })
            case "vco:ingress:ServerPool":
                return new ServerPool(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("vco", "ingress", _module)
