// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class VirtualMachineNIC extends pulumi.CustomResource {
    /**
     * Get an existing VirtualMachineNIC resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): VirtualMachineNIC {
        return new VirtualMachineNIC(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vco:virtual_machine:VirtualMachineNIC';

    /**
     * Returns true if the given object is an instance of VirtualMachineNIC.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VirtualMachineNIC {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VirtualMachineNIC.__pulumiType;
    }

    public readonly cloudspace_id!: pulumi.Output<string>;
    public readonly customerID!: pulumi.Output<string>;
    public /*out*/ readonly device_name!: pulumi.Output<string>;
    public readonly external_cloudspace_id!: pulumi.Output<string>;
    public readonly external_network_id!: pulumi.Output<number>;
    public readonly external_network_ip!: pulumi.Output<string | undefined>;
    public readonly external_network_type!: pulumi.Output<string | undefined>;
    public /*out*/ readonly ip_address!: pulumi.Output<string>;
    public /*out*/ readonly mac_address!: pulumi.Output<string>;
    public readonly model!: pulumi.Output<string>;
    public /*out*/ readonly network_id!: pulumi.Output<number>;
    public /*out*/ readonly nic_type!: pulumi.Output<string>;
    public readonly token!: pulumi.Output<string>;
    public readonly url!: pulumi.Output<string>;
    public readonly vm_id!: pulumi.Output<number>;

    /**
     * Create a VirtualMachineNIC resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VirtualMachineNICArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.cloudspace_id === undefined) && !opts.urn) {
                throw new Error("Missing required property 'cloudspace_id'");
            }
            if ((!args || args.customerID === undefined) && !opts.urn) {
                throw new Error("Missing required property 'customerID'");
            }
            if ((!args || args.external_network_id === undefined) && !opts.urn) {
                throw new Error("Missing required property 'external_network_id'");
            }
            if ((!args || args.token === undefined) && !opts.urn) {
                throw new Error("Missing required property 'token'");
            }
            if ((!args || args.url === undefined) && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            if ((!args || args.vm_id === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vm_id'");
            }
            resourceInputs["cloudspace_id"] = args ? args.cloudspace_id : undefined;
            resourceInputs["customerID"] = args ? args.customerID : undefined;
            resourceInputs["external_cloudspace_id"] = args ? args.external_cloudspace_id : undefined;
            resourceInputs["external_network_id"] = args ? args.external_network_id : undefined;
            resourceInputs["external_network_ip"] = args ? args.external_network_ip : undefined;
            resourceInputs["external_network_type"] = args ? args.external_network_type : undefined;
            resourceInputs["model"] = args ? args.model : undefined;
            resourceInputs["token"] = args ? args.token : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
            resourceInputs["vm_id"] = args ? args.vm_id : undefined;
            resourceInputs["device_name"] = undefined /*out*/;
            resourceInputs["ip_address"] = undefined /*out*/;
            resourceInputs["mac_address"] = undefined /*out*/;
            resourceInputs["network_id"] = undefined /*out*/;
            resourceInputs["nic_type"] = undefined /*out*/;
        } else {
            resourceInputs["cloudspace_id"] = undefined /*out*/;
            resourceInputs["customerID"] = undefined /*out*/;
            resourceInputs["device_name"] = undefined /*out*/;
            resourceInputs["external_cloudspace_id"] = undefined /*out*/;
            resourceInputs["external_network_id"] = undefined /*out*/;
            resourceInputs["external_network_ip"] = undefined /*out*/;
            resourceInputs["external_network_type"] = undefined /*out*/;
            resourceInputs["ip_address"] = undefined /*out*/;
            resourceInputs["mac_address"] = undefined /*out*/;
            resourceInputs["model"] = undefined /*out*/;
            resourceInputs["network_id"] = undefined /*out*/;
            resourceInputs["nic_type"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
            resourceInputs["vm_id"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VirtualMachineNIC.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a VirtualMachineNIC resource.
 */
export interface VirtualMachineNICArgs {
    cloudspace_id: pulumi.Input<string>;
    customerID: pulumi.Input<string>;
    external_cloudspace_id?: pulumi.Input<string>;
    external_network_id: pulumi.Input<number>;
    external_network_ip?: pulumi.Input<string>;
    external_network_type?: pulumi.Input<string>;
    model?: pulumi.Input<string>;
    token: pulumi.Input<string>;
    url: pulumi.Input<string>;
    vm_id: pulumi.Input<number>;
}
