// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Inputs
{

    public sealed class FirewallCustomArgs : global::Pulumi.ResourceArgs
    {
        [Input("cdrom_id")]
        public Input<int>? Cdrom_id { get; set; }

        [Input("disk_size")]
        public Input<int>? Disk_size { get; set; }

        [Input("image_id")]
        public Input<int>? Image_id { get; set; }

        [Input("memory")]
        public Input<int>? Memory { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("vcpus")]
        public Input<int>? Vcpus { get; set; }

        public FirewallCustomArgs()
        {
        }
        public static new FirewallCustomArgs Empty => new FirewallCustomArgs();
    }
}
