// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vco.Resources.Inputs
{

    public sealed class OptionsArgs : global::Pulumi.ResourceArgs
    {
        [Input("health_check", required: true)]
        public Input<Inputs.HealthCheckArgs> Health_check { get; set; } = null!;

        [Input("sticky_session_cookie", required: true)]
        public Input<Inputs.StickySessionCookieArgs> Sticky_session_cookie { get; set; } = null!;

        public OptionsArgs()
        {
        }
        public static new OptionsArgs Empty => new OptionsArgs();
    }
}
